name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            app-name: lorocmsdrupal
            images: drupal:9.4.2
            